from loguru import logger
from starlette.exceptions import HTTPException

from apps.hik.models.person import Person as HikPerson
from apps.hr.hooks.base import BaseHikHook
from apps.hr.tables import Person


class PersonHook(BaseHikHook):
    """Hook for Person CRUD operations with HikVision API integration"""

    async def pre_save(self, row: Person) -> Person:
        """
        Add person to HikVision before saving to database.

        Args:
            row: Person row to be created

        Returns:
            Person row updated with person_id from HikVision API
        """
        try:
            client = await self._get_client()

            # Get group_id from related group
            group_obj = await row.group.get_related()
            if group_obj is None:
                raise HTTPException(
                    status_code=404,
                    detail="Group not found for person %s" % row.code,
                )

            # Prepare person data for HikVision API
            hik_person = HikPerson(
                person_id=None,  # Will be generated by HikVision
                group_id=group_obj.group_id,
                person_code=row.code,
                first_name=row.first_name,
                last_name=row.last_name,
                gender=2,  # Unknown by default
                start_date=row.start_date,
                end_date=row.end_date,
            )

            # Call HikVision API to add person
            person_id = await client.add_person(person=hik_person)

            # Store person_id in the database row
            row.person_id = person_id

            logger.info(
                "Added person to HikVision: %s - %s %s (%s)"
                % (person_id, row.first_name, row.last_name, row.code)
            )

            # If person has face data, update it
            if row.face_data:
                await client.update_person_photo(
                    person_id=person_id,
                    photo_base64=row.face_data,
                )
                logger.info("Updated person photo for %s" % person_id)
            # If person has PIN code, update it
            if row.pin_code:
                await client.update_person_pincode(
                    person_id=person_id,
                    pin_code=row.pin_code,
                )
                logger.info("Updated person PIN code for %s" % person_id)

            return row

        except Exception as e:
            logger.error("Failed to add person to HikVision: %s" % str(e))
            raise HTTPException(
                status_code=500,
                detail="Failed to add person to HikVision: %s" % str(e),
            )
        finally:
            await self._close_client()

    async def pre_patch(self, row_id: str, values: dict) -> dict:
        """
        Update person in HikVision before updating database.

        Args:
            row_id: ID of the person to update
            values: Dictionary of fields to update

        Returns:
            Updated values dictionary
        """
        try:
            # Fetch current person from database
            current_person = await Person.objects().get(Person.id == row_id)

            if current_person is None:
                raise ValueError(f"Person with id {row_id} not found")

            if not current_person.person_id:
                raise ValueError(
                    f"Person {current_person.code} has no person_id from HikVision"
                )

            client = await self._get_client()

            # Update photo if face_data is in values
            if "face_data" in values and values["face_data"]:
                await client.update_person_photo(
                    person_id=current_person.person_id,
                    photo_base64=values["face_data"],
                )
                logger.info("Updated person photo for %s" % current_person.person_id)

            # Update PIN code if pin_code is in values
            if "pin_code" in values and values["pin_code"]:
                await client.update_person_pincode(
                    person_id=current_person.person_id,
                    pin_code=values["pin_code"],
                )
                logger.info("Updated person PIN code for %s" % current_person.person_id)

            logger.info(
                "Updated person in HikVision: %s - %s %s"
                % (
                    current_person.person_id,
                    current_person.first_name,
                    current_person.last_name,
                )
            )

            return values

        except Exception as e:
            logger.error("Failed to update person in HikVision: %s" % str(e))
            raise HTTPException(
                status_code=500,
                detail="Failed to update person in HikVision: %s" % str(e),
            )
        finally:
            await self._close_client()

    async def pre_delete(self, row_id: str) -> None:
        """
        Delete person from HikVision before deleting from database.

        Args:
            row_id: ID of the person to delete
        """
        try:
            # Fetch person from database
            person = await Person.objects().get(Person.id == row_id)

            if person is None:
                raise HTTPException(
                    status_code=404, detail="Person with id %s not found" % row_id
                )

            if not person.person_id:
                raise HTTPException(
                    status_code=400,
                    detail="Person %s has no person_id from HikVision" % person.code,
                )

            client = await self._get_client()

            # Delete person from HikVision
            await client.delete_person(person_id=person.person_id)

            logger.info(
                "Deleted person from HikVision: %s - %s"
                % (person.person_id, person.code)
            )

        except Exception as e:
            logger.error("Failed to delete person from HikVision: %s" % str(e))
            raise HTTPException(
                status_code=500,
                detail="Failed to delete person from HikVision: %s" % str(e),
            )
        finally:
            await self._close_client()


# Create singleton instance
person_hook = PersonHook()
